var tree = [["Icecave",,"",
                [["Collections","Icecave\/Collections.html","",
                [["Detail","Icecave\/Collections\/Detail.html","",
                [["LinkedListIterator","Icecave\/Collections\/Detail\/LinkedListIterator.html","",
                [        ]]        ]],["Exception","Icecave\/Collections\/Exception.html","",
                [["CollectionExceptionInterface","Icecave\/Collections\/Exception\/CollectionExceptionInterface.html","",
                [        ]],["DuplicateKeyException","Icecave\/Collections\/Exception\/DuplicateKeyException.html"," < RuntimeException",
                [        ]],["EmptyCollectionException","Icecave\/Collections\/Exception\/EmptyCollectionException.html"," < UnderflowException",
                [        ]],["IndexException","Icecave\/Collections\/Exception\/IndexException.html"," < OutOfBoundsException",
                [        ]],["UnknownKeyException","Icecave\/Collections\/Exception\/UnknownKeyException.html"," < OutOfBoundsException",
                [        ]]        ]],["Iterator","Icecave\/Collections\/Iterator.html","",
                [["AssociativeIterator","Icecave\/Collections\/Iterator\/AssociativeIterator.html","",
                [        ]],["RandomAccessIterator","Icecave\/Collections\/Iterator\/RandomAccessIterator.html","",
                [        ]],["SequentialKeyIterator","Icecave\/Collections\/Iterator\/SequentialKeyIterator.html"," < IteratorIterator",
                [        ]],["Traits","Icecave\/Collections\/Iterator\/Traits.html","",
                [        ]],["TraitsProviderInterface","Icecave\/Collections\/Iterator\/TraitsProviderInterface.html","",
                [        ]],["UnpackIterator","Icecave\/Collections\/Iterator\/UnpackIterator.html","",
                [        ]]        ]],["AssociativeInterface","Icecave\/Collections\/AssociativeInterface.html","",
                [        ]],["Collection","Icecave\/Collections\/Collection.html","",
                [        ]],["CollectionInterface","Icecave\/Collections\/CollectionInterface.html","",
                [        ]],["IterableInterface","Icecave\/Collections\/IterableInterface.html","",
                [        ]],["LinkedList","Icecave\/Collections\/LinkedList.html","",
                [        ]],["Map","Icecave\/Collections\/Map.html","",
                [        ]],["MutableAssociativeInterface","Icecave\/Collections\/MutableAssociativeInterface.html","",
                [        ]],["MutableCollectionInterface","Icecave\/Collections\/MutableCollectionInterface.html","",
                [        ]],["MutableIterableInterface","Icecave\/Collections\/MutableIterableInterface.html","",
                [        ]],["MutableRandomAccessInterface","Icecave\/Collections\/MutableRandomAccessInterface.html","",
                [        ]],["MutableSequenceInterface","Icecave\/Collections\/MutableSequenceInterface.html","",
                [        ]],["PackageInfo","Icecave\/Collections\/PackageInfo.html","",
                [        ]],["PriorityQueue","Icecave\/Collections\/PriorityQueue.html"," < Queue",
                [        ]],["Queue","Icecave\/Collections\/Queue.html","",
                [        ]],["QueuedAccessInterface","Icecave\/Collections\/QueuedAccessInterface.html","",
                [        ]],["RandomAccessInterface","Icecave\/Collections\/RandomAccessInterface.html","",
                [        ]],["SequenceInterface","Icecave\/Collections\/SequenceInterface.html","",
                [        ]],["Set","Icecave\/Collections\/Set.html","",
                [        ]],["SetInterface","Icecave\/Collections\/SetInterface.html","",
                [        ]],["SinglyLinkedList","Icecave\/Collections\/SinglyLinkedList.html","",
                [        ]],["Stack","Icecave\/Collections\/Stack.html","",
                [        ]],["Vector","Icecave\/Collections\/Vector.html","",
                [        ]]        ]]        ]]        ]

